### ISSUE TITLE
Returning a list of promises

### ISSUE THREAD

**Issue by winstonma** [miklcct/js-kmb-api#1]
First of all it's not an issue. I would consider it as a brainstorm.

For example, the `getStopRoutes()` provides list of infos (route, stop) that passes through a particular stop. It returns a list of results. As the returned info is in fact independent, would it be better if the function either

- Split into 2 functions, e.g.
```
getStop(stopID).then(routes =>
  routes.forEach(route =>
    getStopRoutes(route, stopID).then(
       // Get the ETA, or put the result onto the UI
    )
  )
)
```
, or

- Returning a list of promises

I am not a javascript guy so I am not sure what is best. It's just my two cent.

**Comment by miklcct** [comment]
The purpose of this function is to "list the actual variants which passes through a particular stop". There is logic to find which variant sin the route pass through the specified stop. The logic is to compensate for the fact that there is no direct API by KMB to do this, in contrast to NWFB where a single API call can list out the actual variants already.

**Comment by winstonma** [comment]
If the objective is to create a NWFB-like function. Then it make sense.
