### ISSUE TITLE
Include stop.name in stop.getStoppings()

### ISSUE THREAD

**Issue by winstonma** [miklcct/js-kmb-api#3]
Here is one of the returned value in `stop.getStoppings()`

```
{
   "stop":{
      "id":"MA01-T-1100-0"
   },
   "variant":{
      "route":{
         "number":"N680",
         "bound":1
      },
      "serviceType":1,
      "origin":"Kam Ying Court",
      "destination":"Central (Macau Ferry)",
      "description":""
   },
   "direction":"F",
   "sequence":3,
   "fare":27.3
}
```

In the web version the `stop.name` is included, would it be possible to include it in the JS library? If not, then is it possible that I could find the name of the stop? Thanks in advance

**Comment by miklcct** [comment]
`stop.name` is now a dynamic property taken from the cache. You can access it as `stop.name`
