### ISSUE TITLE
[Feature Request] Support display of Hong Kong character

### ISSUE THREAD

**Issue by winstonma** [miklcct/js-kmb-api#4]
Just found that [hkscs_unicode_converter](https://github.com/chaklim/hkscs_unicode_converter) could convert the Hong Kong character into displayable character. Also I tried the code in [RunKit](https://runkit.com/winstonma/5f9c249485a895001b5bb1d2) and it seems work.

**Comment by miklcct** [comment]
fixed in 3.1.0
