### ISSUE TITLE
stop.getStoppings() and KMB API returns different number of routes

### ISSUE THREAD

**Issue by winstonma** [miklcct/js-kmb-api#5]
I found that `stop.getStoppings()` works in most of the cases but in one stop there is less returned value. Please see the attached [Runkit](https://runkit.com/winstonma/5f9c249485a895001b5bb1d2).

Thank you very very much

**Comment by miklcct** [comment]
The provided runkit is wrong. the Stop constructor does not accept null as the second parameter in the current version of the library. You need to specify only the stop ID.

**Comment by winstonma** [comment]
I see. Maybe the usage of the API is not right. But there is no doubt that the stopping info could be obtained solely by the `stopID`. Therefore the missing link is the missing stop name, which is obtainable from the `stopID` itself.

For the `getStoppings()` function, is it possible to fill the stop name (if empty) before running the actual `getStoppings()` logic?

Currently I am using the following code to obtain the correct getStoppings:
```
const stopTest = new kmb.Stop(stopID, null);
await stopTest.getStoppings()
    .then(data => data[0].stop.name)
    .then(stopName => {
        const stop = new kmb.Stop(stopID, stopName);
        stop.getStoppings()
          .then(data => {
            console.log(data);
            const busRoutes = [...new Set(data.map(item => item.variant.route.number))];
            console.log(`Routes for the stop: ${busRoutes}`);
          })
      })
```
This could fix the problem but it could be more efficient if `getStoppings()` is called one time only.

Thanks

**Comment by miklcct** [comment]
You can't use `null` as the second parameter, either `undefined` or the correct stop name.

**Comment by winstonma** [comment]
Thank you very much for clarifying
