### ISSUE TITLE
Support non-browser caching

### ISSUE THREAD

**Issue by winstonma** [miklcct/js-kmb-api#9]
I am currently using [node-cache](https://www.npmjs.com/package/node-cache) and applied the module on [Runkit](https://runkit.com/winstonma/5fbb70ab959074001a8f167b). You know the caching behavior couldn't be observed on Runkit as it would clean up everything between each execution but it works locally.

Just wonder if caching could be supported. Thanks a lot

**Comment by miklcct** [comment]
Pass a storage when constructing the API

**Comment by winstonma** [comment]
Thanks

I assumed the localStorage only works on browser so I didn't pay attention. It works and thanks a lot.
